### ISSUE TITLE
Runtime crash - React Native Huawei 

### ISSUE THREAD

**Issue by imkrishh** [infobip/mobile-messaging-react-native-plugin#48]
React Native Infobip for Huawei app crashes in release build after update of `mobile-messaging-react-native-plugin v6.3.3`
 
`mobile-messaging-sdk-huawei v2.2.3`

```
Fatal Exception: java.lang.RuntimeException: Could not invoke ReactNativeMobileMessaging.init
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:219)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:929)
```

React Native - 0.65.1

**Comment by riskpp** [comment]
Hi @imkrishh, we support only iOS and Android platforms for React Native right now.
And we've released update for mobile-messaging-sdk-huawei with support of AndroidX - https://github.com/infobip/mobile-messaging-sdk-huawei/releases/tag/3.0.0-rc1, but I'm not sure how do you plan to use it together..

**Comment by quantumarun** [comment]
@riskpp  We currently have the native code for Infobip Huawei Implementation which was done in collaboration with Infobip Team somewhere around 2019. Now this is causing issue in upgrading the Infobip version. How can we take this forward.
